### ISSUE TITLE
Tests failing on install

### ISSUE THREAD

**Issue by MikeWise2718** [Microsoft/TypeScript-TmLanguage#370]
I installed this, am quite new to this tmLanguage thing, wanted to see if I could get a syntax highligher for a config fiile which has some unusual structure. So it seemed reasonable to start by getting this working locally and then use it as a template. 2 problems.

1. It was difficult to install.
2. A lot of the tests are now failing now that I have got it installed.

I think I followed all the brief instructions. Or did I forget something obvious?

More detail:

-------------------------------------------------------------------------

1. There was no list of dependencies. I am working with a fairly new (2 weeks old) Windows 10 installation. In order to get this to work I had to:

-  Install node.js (v6.9.1)
-  Install Windows SDK 8.1
-  Install C++ tools on Visual Studio 2015
-  Setup a virtual environment with Python 2.7 for the test build (as my default is Python 3.5) - I used conda for that
-  Ensure that **CL.exe** (in the tools) was in the path (at **C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin)**

Then I could build it, albeit with quite a few warnings compling **regposix.c** of the form:
```
..\deps\onig\regcomp.c(563): warning C4311: 'type cast': pointer truncation from 'OnigUChar *' to 'unsigned int' [C:\lo
cal\TypeScript-TmLanguage\tests\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(1344): warning C4312: 'type cast': conversion from 'OnigStackIndex' to 'void *' of greater size
[C:\local\TypeScript-TmLanguage\tests\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(1348): warning C4312: 'type cast': conversion from 'OnigStackIndex' to 'void *' of greater size
[C:\local\TypeScript-TmLanguage\tests\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(1364): warning C4312: 'type cast': conversion from 'OnigStackIndex' to 'void *' of greater size
[C:\local\TypeScript-TmLanguage\tests\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(1368): warning C4312: 'type cast': conversion from 'OnigStackIndex' to 'void *' of greater size
[C:\local\TypeScript-TmLanguage\tests\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(1672): warning C4311: 'type cast': pointer truncation from 'OnigUChar *' to 'unsigned int' [C:\l
ocal\TypeScript-TmLanguage\tests\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(1737): warning C4311: 'type cast': pointer truncation from 'OnigUChar *' to 'unsigned int' [C:\l
ocal\TypeScript-TmLanguage\tests\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(2082): warning C4311: 'type cast': pointer truncation from 'void *' to 'OnigStackIndex' [C:\loca
l\TypeScript-TmLanguage\tests\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(2096): warning C4311: 'type cast': pointer truncation from 'void *' to 'OnigStackIndex' [C:\loca
l\TypeScript-TmLanguage\tests\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(2113): warning C4311: 'type cast': pointer truncation from 'void *' to 'OnigStackIndex' [C:\loca
l\TypeScript-TmLanguage\tests\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(2119): warning C4311: 'type cast': pointer truncation from 'void *' to 'OnigStackIndex' [C:\loca
l\TypeScript-TmLanguage\tests\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(2153): warning C4312: 'type cast': conversion from 'OnigStackIndex' to 'void *' of greater size
[C:\local\TypeScript-TmLanguage\tests\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(2157): warning C4312: 'type cast': conversion from 'OnigStackIndex' to 'void *' of greater size
[C:\local\TypeScript-TmLanguage\tests\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(2185): warning C4312: 'type cast': conversion from 'OnigStackIndex' to 'void *' of greater size
[C:\local\TypeScript-TmLanguage\tests\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(2189): warning C4312: 'type cast': conversion from 'OnigStackIndex' to 'void *' of greater size
[C:\local\TypeScript-TmLanguage\tests\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(2217): warning C4312: 'type cast': conversion from 'OnigStackIndex' to 'void *' of greater size
[C:\local\TypeScript-TmLanguage\tests\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(2221): warning C4312: 'type cast': conversion from 'OnigStackIndex' to 'void *' of greater size
[C:\local\TypeScript-TmLanguage\tests\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(2256): warning C4312: 'type cast': conversion from 'OnigStackIndex' to 'void *' of greater size
[C:\local\TypeScript-TmLanguage\tests\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(2260): warning C4312: 'type cast': conversion from 'OnigStackIndex' to 'void *' of greater size
[C:\local\TypeScript-TmLanguage\tests\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(2372): warning C4312: 'type cast': conversion from 'OnigStackIndex' to 'OnigUChar *' of greater
size [C:\local\TypeScript-TmLanguage\tests\node_modules\oniguruma\build\oniguruma.vcxproj]
..\deps\onig\regexec.c(2395): warning C4312: 'type cast': conversion from 'OnigStackIndex' to 'OnigUChar *' of greater
size [C:\local\TypeScript-TmLanguage\tests\node_modules\oniguruma\build\oniguruma.vcxproj]
```

2. Now the tests run, but quite a few fail including the first one:

```
157 passing (424ms)
  43 failing

  1) Compare generated with baselines Comparing Abstracts.baseline.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  2) Compare generated with baselines Comparing ArrowFunctionInsideTypeAssertion.baseline.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  3) Compare generated with baselines Comparing Comments.baseline.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  4) Compare generated with baselines Comparing enumMemberWithIntializer.baseline.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  5) Compare generated with baselines Comparing FunctionMethodOverloads.baseline.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  6) Compare generated with baselines Comparing FunctionMethodParameters.baseline.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  7) Compare generated with baselines Comparing FunctionMethodReturnTypes.baseline.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  8) Compare generated with baselines Comparing Issue110.baseline.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  9) Compare generated with baselines Comparing Issue110.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  10) Compare generated with baselines Comparing Issue124.baseline.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  11) Compare generated with baselines Comparing Issue124.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  12) Compare generated with baselines Comparing Issue149.baseline.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  13) Compare generated with baselines Comparing Issue156.baseline.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  14) Compare generated with baselines Comparing Issue156.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  15) Compare generated with baselines Comparing Issue186.baseline.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  16) Compare generated with baselines Comparing Issue191.baseline.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  17) Compare generated with baselines Comparing Issue208.baseline.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  18) Compare generated with baselines Comparing Issue262.baseline.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  19) Compare generated with baselines Comparing Issue262.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  20) Compare generated with baselines Comparing Issue28.baseline.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  21) Compare generated with baselines Comparing Issue280.baseline.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  22) Compare generated with baselines Comparing Issue288.baseline.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  23) Compare generated with baselines Comparing Issue32.baseline.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  24) Compare generated with baselines Comparing Issue32.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  25) Compare generated with baselines Comparing Issue335.baseline.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  26) Compare generated with baselines Comparing Issue37.baseline.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  27) Compare generated with baselines Comparing Issue37.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  28) Compare generated with baselines Comparing Issue44.baseline.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  29) Compare generated with baselines Comparing Issue5.baseline.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  30) Compare generated with baselines Comparing Issue5.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  31) Compare generated with baselines Comparing Issue63.baseline.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  32) Compare generated with baselines Comparing Issue82.baseline.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  33) Compare generated with baselines Comparing Issue82.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  34) Compare generated with baselines Comparing Issue89.baseline.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  35) Compare generated with baselines Comparing Issue89.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  36) Compare generated with baselines Comparing Issue90.baseline.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  37) Compare generated with baselines Comparing Issue90.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  38) Compare generated with baselines Comparing Issue96.baseline.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  39) Compare generated with baselines Comparing multipleVariableDeclaration.baseline.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  40) Compare generated with baselines Comparing ParameterProperties.baseline.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  41) Compare generated with baselines Comparing pr48_noSemiColon.baseline.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  42) Compare generated with baselines Comparing SyntacticallyIncorrectStrings.baseline.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)

  43) Compare generated with baselines Comparing TsxSamples.baseline.txt should be the same:
     AssertionError: expected false to be true
      at Context.<anonymous> (test.js:22:70)



npm ERR! Test failed.  See above for more details.

**Comment by sheetalkamat** [comment]
@MikeWise2718 did you follow these steps: https://github.com/Microsoft/TypeScript-TmLanguage#tests 
I also have run ```npm install -g --production windows-build-tools``` locally on my machine but not sure if it is required.

After running the tests if you are still seeing the errors, would it be possible for you to compare folder tests\baselines and tests\generated to see what is the difference and see what might be going on.

We have tests running on commits/PRs (eg. [latest commit run](https://ci.appveyor.com/project/zhengbli/typescript-tmlanguage/build/1.0.370)) and they seem to be working fine. Also they seem to run locally as well. So more information might be helpful to investigate this further.

**Comment by sheetalkamat** [comment]
@MikeWise2718  Please reopen this with how to repro this so that we can investigate it.
